
site_name: DocMan_MCP Documentation
site_description: Comprehensive document management system with AI-powered summarization
site_author: DocMan_MCP Team
site_url: https://docman-mcp.example.com

repo_name: DocMan_MCP
repo_url: https://github.com/your-org/DocMan_MCP

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md
  - API Reference: api.md
  - Project Structure: structure.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/DocMan_MCP
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/your-org/docman-mcp

copyright: Copyright &copy; 2024 DocMan_MCP Team

